### ISSUE TITLE
RAM参数修改无效果

### ISSUE THREAD

**Issue by BiDuang** [baibao132/SikaDeerLauncher#16]
阁下的启动函数如下：
```await game.StartGame(version, javaPath, RAM, playerName);```
但是无论如何更改RAM参数，包括变量或直接赋值，最终在游戏中呈现出来的都是512MB

**Comment by BiDuang** [comment]
测试环境为1.17.1

**Comment by baibao132** [comment]
今天我会去该核实问题的

**Comment by BiDuang** [comment]
您启动游戏试试，按f3打开调试，您应当会看到错误的ram

**Comment by BiDuang** [comment]
那能麻烦您留个联系方式吗？我将我的代码样例给您测试下

**Comment by baibao132** [comment]
2817541592
